### ISSUE TITLE
app()->withSchedulle() не отображает задач

### ISSUE THREAD

**Issue by origami4love** [yurizoom/moonshine-scheduling#1]
Привет!

Если сконфигурировать приложение
```
return Application::configure(basePath: dirname(__DIR__))
    ->withRouting(
        web: __DIR__ . '/../routes/web.php',
        commands: __DIR__ . '/../routes/console.php',
        health: '/up',
    )
    ->withSchedule(new ScheduleHandler())
    })->create();
```

то в админке список команд не выводится, 
![image](https://github.com/yurizoom/moonshine-scheduling/assets/173542959/2d377b03-68e1-45f2-9dc9-e1c5ac9ab43e)

а в консоли они есть
![image](https://github.com/yurizoom/moonshine-scheduling/assets/173542959/5a0e4839-a3da-4a34-830f-b012dfe6521d)

**Comment by yurizoom** [comment]
Исправлено. Обновите до версии 1.1.1
