### ISSUE TITLE
Автоматический запуск заданий

### ISSUE THREAD

**Issue by Aporrhia** [yurizoom/moonshine-scheduling#2]
Добрый день!
Возникли пару проблем. 

### 1.

После устанвки, при переходе на страницу с расписанием, в дебаггере выводится следующая ошибка:

`Automatic conversion of false to array is deprecated in C:\xampp\htdocs\project\vendor\yurizoom\moonshine-scheduling\src\CronSchedule.php on line 757`

Её возможно убрать таким образом:
**CronSchedule.php**
`private bool|array $_lang = false; ` ->  `private array $_lang;`

Но является ли это правильным решением, не уверен.

### 2.

Не запускаются _автоматически_ задания после их создания и добавления в `/routes/console.php`. При ручном нажатии на кнопку **Run**, на странице с расписанием задания выполняются. Только автоматически через выставленное время они не запускаются.

Возможно ли, что необходимо запускать следующую команду для запуска на сервере:
`* * * * * cd /path-to-your-project && php artisan schedule:run >> /dev/null 2>&1`

Заранее спасибо.

**Comment by yurizoom** [comment]
Добрый день!
1. Спасибо за замечание. Поправил
2. Все верно, нужно в cron добавлять запуск планировщика, как указано в документации к Laravel. Данное расширение выступает лишь инструментом, чтобы можно было удобно смотреть и запускать задания не используя консоль
